config/routes.rb
Rails.application.routes.draw do
  resources :storages
  resources :products
  resources :books
  resources :posts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "users#index"
end

app/models/storage.rb
class Storage < ApplicationRecord
end

app/controllers/storages_controller.rb
class StoragesController < ApplicationController
  before_action :set_storage, only: %i[ show edit update destroy ]

  # GET /storages or /storages.json
  def index
    @storages = Storage.all
  end

  # GET /storages/1 or /storages/1.json
  def show
  end

  # GET /storages/new
  def new
    @storage = Storage.new
  end

  # GET /storages/1/edit
  def edit
  end

  # POST /storages or /storages.json
  def create
    @storage = Storage.new(storage_params)

    respond_to do |format|
      if @storage.save
        format.html { redirect_to storage_url(@storage), notice: "Storage was successfully created." }
        format.json { render :show, status: :created, location: @storage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /storages/1 or /storages/1.json
  def update
    respond_to do |format|
      if @storage.update(storage_params)
        format.html { redirect_to storage_url(@storage), notice: "Storage was successfully updated." }
        format.json { render :show, status: :ok, location: @storage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @storage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storages/1 or /storages/1.json
  def destroy
    @storage.destroy!

    respond_to do |format|
      format.html { redirect_to storages_url, notice: "Storage was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_storage
      @storage = Storage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def storage_params
      params.require(:storage).permit(:name, :description)
    end
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/views/storages/_form.html.erb
<%= form_with(model: storage) do |form| %>
  <% if storage.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(storage.errors.count, "error") %> prohibited this storage from being saved:</h2>

      <ul>
        <% storage.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/storages/_storage.html.erb
<div id="<%= dom_id storage %>">
  <p>
    <strong>Name:</strong>
    <%= storage.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= storage.description %>
  </p>

</div>

app/views/storages/edit.html.erb
<h1>Editing storage</h1>

<%= render "form", storage: @storage %>

<br>

<div>
  <%= link_to "Show this storage", @storage %> |
  <%= link_to "Back to storages", storages_path %>
</div>

app/views/storages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Storages</h1>

<div id="storages">
  <% @storages.each do |storage| %>
    <%= render storage %>
    <p>
      <%= link_to "Show this storage", storage %>
    </p>
  <% end %>
</div>

<%= link_to "New storage", new_storage_path %>

app/views/storages/new.html.erb
<h1>New storage</h1>

<%= render "form", storage: @storage %>

<br>

<div>
  <%= link_to "Back to storages", storages_path %>
</div>

app/views/storages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @storage %>

<div>
  <%= link_to "Edit this storage", edit_storage_path(@storage) %> |
  <%= link_to "Back to storages", storages_path %>

  <%= button_to "Destroy this storage", @storage, method: :delete %>
</div>